version: '3'
services: 
    secondkill-admin:
        build: 
            context: .
        image: secondkill-admin
        container_name: secondkill-admin
        restart: always
        ports: 
            - 8888:8888
        networks: 
            - secondkill_default
        external_links: 
            - secondkill-zuul

networks: 
    secondkill_default:
        external: true